### PR TITLE
Fix undefined behaviour for `GestaltId` when starting agent

### LINKED ISSUE #797: Fix undefined behaviour error message coming from background tasks
### Specification

When starting an existing agent that hasn't run for a little while we get the following warning logger message.

image

We'll need to find the cause for this and fix it. There aren't many tasks that persist between restarts so it should be simple to narrow down. But in that vein we need to make the following changes to make these problems more clear.

1. The message should mention which task handler failed.
2. Any usage of `utils.never()` should include a descriptive message of what shouldn't be happening. so we need to update all usage of never in a task handler.

### Tasks

1. Update the warning log for a failed task handler to include more information about what task was running.
2. Update the `utils.never()` usages in task handlers to include proper failure descriptions.
3. Find and determine the failure occurring here and fix it.

### PR DESCRIPTION
**Pull request by aryanjassal**
### Description

When starting the agent after approximately 1 hour, an error is thrown like such:

```
WARN:polykey.PolykeyAgent.task v0ppdq4uibpo01417n072jft4io:Failed - Reason: ErrorUtilsUndefinedBehaviour("failed to decode vertex GestaltId "undefined"")
```

This is caused due to a minor typo in the discovery domain. This has been resolved in this PR, and similar messages should no longer happen.

### Issues Fixed

* Fixes #797 (REF ENG-400)

### Tasks

- [x] 1. Fix the undefined behaviour error

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by aryanjassal** [comment]
This PR depends on https://github.com/MatrixAI/Polykey/pull/838.

After that PR has been merged, this can be too.

**Comment by CMCDragonkai** [comment]
That's great how can we prevent regressions of this nature in the future? Types or fast check tests?

**Comment by aryanjassal** [comment]
> That's great how can we prevent regressions of this nature in the future? Types or fast check tests?

https://github.com/MatrixAI/Polykey/issues/797#issuecomment-2467292822

**Review by tegefaulkes — APPROVED** [review]

**Comment by aryanjassal** [comment]
I ran manual sanity checks for this change by printing the status of the actual task in `TaskManager.startTask()` and by setting the time interval to 1 second so it will trigger continuously. That resulted in zero errors and the rediscovery triggering each second.

This means that the changes made was successful in fixing this issue.

**Comment by aryanjassal** [comment]
Now that the CI is passing and the changes are approved, I will be merging this and making a release.

**Pull request merged**
