### PR TITLE
chore: making `nixpkgs-matrix` an indirect input

### PR DESCRIPTION
**Pull request by tegefaulkes**
### Description

This PR incorporates the new indirect flake input system.

### Tasks

- [x] 1. Update `flake.nix` to use indirect inputs

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by tegefaulkes** [comment]
I'm doing this as a PR here for reference and just so that @brynblack can check I got the change right.

**Comment by tegefaulkes** [comment]
Ah, I can't seem to find `nixpkgs-matrix` in the flake registries. I possibly have to do a nix rebuild to get that into my profile right?

**Comment by tegefaulkes** [comment]
Ok, I only had to add it to the registry with `nix registry add nixpkgs-matrix github:MatrixAI/nixpkgs-matrix`.

**Comment by brynblack** [comment]
This looks good. I think it can be merged once we have all our other repos ready for the transition.

**Review by brynblack — COMMENTED** [review]
Nothing to change. Maybe add some documentation to the `README.md`.

**Pull request merged**
