### PR TITLE
ci: merge staging to master

### PR DESCRIPTION
**Pull request by maxwell-aiden**
This is an automatic PR generated by the pipeline CI/CD. This will be automatically fast-forward merged if successful.

### CODE REVIEW

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1271241831 for eb284fc2685a03129a3a9d0c22996d63900c0925

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1271241831

**Comment by CMCDragonkai** [comment]
Test failure: https://gitlab.com/MatrixAI/open-source/Polykey/-/jobs/6735737873

**Comment by CMCDragonkai** [comment]
@tegefaulkes property test:

```
✕ handleClaimIdentity (with seed=1499257462) (20097 ms)
  ● IdentitiesManager › handleClaimIdentity (with seed=1499257462)
    Property failed after 1 tests
    { seed: 1499257462, path: "0:76:76:76:76:76", endOnFailure: true }
    Counterexample: ["toString",{"accessToken":"    IiV*eQ","refreshToken":" E@J%%0","accessTokenExpiresIn":8,"refreshTokenExpiresIn":88802816}]
    Shrunk 5 time(s)
    Got TypeError: links.push is not a function
      160 |       : [];
      161 |     const links = this.userLinks[authIdentityId];
    > [162](https://gitlab.com/MatrixAI/open-source/Polykey/-/jobs/6735737873#L162) |     links.push(linkId);
          |           ^
      [163](https://gitlab.com/MatrixAI/open-source/Polykey/-/jobs/6735737873#L163) |     return {
      164 |       id: linkId,
      165 |       url: 'test.com',
      at TestProvider.push [as publishClaim] (tests/identities/TestProvider.ts:162:11)
      at src/identities/IdentitiesManager.ts:280:39
      at constructor_.addClaim (src/sigchain/Sigchain.ts:449:20)
      at withF (node_modules/@matrixai/resources/src/utils.ts:24:12)
      at constructor_.handleClaimIdentity (src/identities/IdentitiesManager.ts:269:5)
      at numRuns (tests/identities/IdentitiesManager.test.ts:361:7)
      at AsyncProperty.run (node_modules/fast-check/lib/check/property/AsyncProperty.generic.js:49:28)
      Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
      at buildError (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:131:15)
      at asyncThrowIfFailed (node_modules/fast-check/lib/check/runner/utils/RunDetailsFormatter.js:148:11)
```

**Comment by CMCDragonkai** [comment]
I removed the vestigial file @tegefaulkes. But the property test failure needs to be checked.

**Comment by maxwell-aiden** [comment]
Pipeline Attempt on 1271334858 for 79ee0888a82fbbd6898a8fcda50aa80d33c54c2a

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1271334858

**Comment by maxwell-aiden** [comment]
Pipeline Succeeded on 1271334858 for 79ee0888a82fbbd6898a8fcda50aa80d33c54c2a

https://gitlab.com/MatrixAI/open-source/Polykey/-/pipelines/1271334858

**Pull request merged**
